#!/usr/bin/env bash
# a script that stops a process withut using kill

#include "sort.h"

void swap_node_ahead(listint_t **list, listint_t **tail, listint_t **shaker);
void swap_node_behind(listint_t **list, listint_t **tail, listint_t **shaker);
void cocktail_sort_list(listint_t **list);

/**
 * swap_node_ahead - swap a node in a listint_t doubly-linked list of ints
 *			with the node ahead of it
 * @list: a pointer to the head of doubly linked list
 * @tail: pointer to the tail of the linked list
 * @shaker: a pointer to the current swapping node of the cocktail shaker algo
 */

void swap_node_ahead(listint_t **list, listint_t **tail, listint_t **shaker)
{
	listint_t *tmp = (*shaker)->next;

	if ((*shaker)->prev != NULL)
		(*shaker)->prev->next = tmp;
	else
		*list = tmp;
	tmp->prev = (*shaker)->prev;
	(*shaker)->next = tmp->next;
	if (tmp->next != NULL)
		tmp->next->prev = *shaker;
	else
		*tail = *shaker;
	(*shaker)->prev = tmp;
	tmp->next = *shaker;
	*shaker = tmp;
}

/**
 * swap_node_behind - swap node in a listint_t doubly linked list of ints
 * @list: A pointer to the head of the linked list
 * @tail: A pointer to the tail of the doubly linked list
 * @shaker: A pointer to the current swapping node of the cocktail shaker algo
 */

void swap_node_behind(listint_t **list, listint_t **tail, listint_t **shaker)
{
	listint_t *tmp = (*shaker)->prev;

	if ((*shaker)->next != NULL)
		(*shaker)->next->prev = tmp;
	else
		*tail = tmp;
	(*shaker)->next = tmp;
	tmp->prev = *shaker;
