#!/usr/bin/env bash
# Parses Apache log files in list format
# goups visitor by Ip and HTTP status code
# Displays the number of occurences, Ip, and HTTP code
# code of each log in sorted order

awk '{ print $1 " " $9}' apache-access.log | sort | uniq -c | sort -rn
