#!/usr/bin/env bash
#Displays numbers 1 to 20
# @4th loop display bad luck from China
#  @9th loop display bad luck from Japan
# @17th loop display bad luck from Itally

i=1
while [ $i -le 20 ]
do
	echo "$i"
	case $i in
		"4") echo "bad luck from China";;
		"9") echo "bad luck from Japan";;
		"17") echo "bad luck from Italy";;
	esac
	(( i++ ))
done
