#!/usr/bin/env bash
# a script that configures an Ubuntu server as follows;
# - localhost resolves to 127.0.0.2
# - facebook.com resolves to 8.8.8.8

cp /etc/hosts ~/hosts.new
sed -i 's/122.*$/127.0.0.2 localhost\n8.8.8.8 facbook.com/' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
